### PR TITLE
ISC server auth

### LINKED ISSUE #45: ISC servers need to authenticate.
The servers should send the authenticate packet to make sure they are allowed to be connected. If they fail to authenticate within the allotted time, disconnect them and possibly block connections from that IP for a short time.

### PR DESCRIPTION
**Pull request by RavenX8**
Closes #45

---
This change is [Reviewable](https://reviewable.io/reviews/dev-osrose/osirose-new/152)

### CODE REVIEW

File: src/char/src/ccharisc.cpp [hunk 1]
```diff
@@ -144,6 +192,10 @@ void CCharISC::OnConnected() {
 bool CCharISC::OnShutdown() {
   logger_->trace("CCharISC::OnShutdown()");
   bool result = true;
+  if(state_ != eSTATE::REGISTERED) {
+    logger_->warn("ISC {} is attempting to shutdown before registering.", get_id());
```
Comment (L3nn0x) [inline src/char/src/ccharisc.cpp:196]: Do we care that much if the server isn't registered before shutting down the connection?

File: src/core/include/config.h [hunk 2]
```diff
@@ -107,6 +109,8 @@ class Config {
   struct MapServer {
     std::string channelName = "Athena";
     std::string charIp = "127.0.0.1";
+    std::string charUser = "char";
+    std::string charPassword = "098f6bcd4621d373cade4e832627b4f6";
```
Comment (L3nn0x) [inline src/core/include/config.h:113]: We should probably use only one user/password for all servers, otherwise it'll just be impossible if/when we have multiple map servers

File: src/char/src/ccharisc.cpp (hunk 1 above)
Comment (RavenX8) [reply src/char/src/ccharisc.cpp:196]: Yes, we don't want to give an attacker the ability to send the login server server_disconnected packets when they aren't a valid server

File: src/core/include/config.h (hunk 2 above)
Comment (RavenX8) [reply src/core/include/config.h:113]: Why would this be impossible? You can use one user/password for all servers if you wanted to.

Comment (L3nn0x) [reply src/core/include/config.h:113]: alright

**Review by L3nn0x — APPROVED** [review]
